{% set name = "elicito" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/elicito-{{ version }}.tar.gz
  sha256: f40a0e33594ee9ed9ea09358c1bdcc14c463920c793ac9a6596eb1aee219e936

build:
  number: 1

requirements:
  host:
    - python {{ python_min }}

outputs:
  - name: elicito
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python {{ python_min }}
        - pdm-backend
        - pip

      run:
        - python >={{ python_min }}
        - tqdm >=4.38
        - numpy >=1.24
        - tensorflow >=2.16.0
        - tensorflow-probability >=0.24.0
        - joblib >=1.4.2
        - tf-keras >=2.16.0

    test:
      imports:
        - elicito
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

  - name: elicito-locked
    build:
      noarch: python

    requirements:
      host:
        - python {{ python_min }}
        - pdm-backend
        - pip

      run:
        - python >={{ python_min }}
        - tqdm >=4.38
        - numpy >=1.24
        - tensorflow >=2.16.0
        - tensorflow-probability >=0.24.0
        - joblib >=1.4.2
        - tf-keras >=2.16.0

    test:
      imports:
        - elicito_locked
      commands:
        - pip check
      requires:
        - pip
        - python {{ python_min }}

about:
  home: https://elicito.readthedocs.io
  summary: A Python package for learning prior distributions based on expert knowledge
  license: Apache-2.0
  license_file: LICENCE
  doc_url: https://elicito.readthedocs.io
  dev_url: https://github.com/florence-bockting/elicito
  description: |
    Learning prior distributions in a Bayesian model
    based on expert knowledge. Uses a simulation-
    based framework that allows learning priors on model
    parameters based on expert knowledge on the outcome
    variable (observable space).

extra:
  feedstock-name: elicito
  recipe-maintainers:
    - florence-bockting
